// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm-ORufKrmkUDgFpjnMJmNwHgPxTZwirg',
    appId: '1:94784010028:web:e54749ef89d151dc41de89',
    messagingSenderId: '94784010028',
    projectId: 'theory-mountain',
    authDomain: 'theory-mountain.firebaseapp.com',
    storageBucket: 'theory-mountain.appspot.com',
    measurementId: 'G-B50MHLQQMH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlmgGtvZXYJnOJ7NYD4vl3Ew2GHoSdKiI',
    appId: '1:94784010028:android:db2873bb9a3483e341de89',
    messagingSenderId: '94784010028',
    projectId: 'theory-mountain',
    storageBucket: 'theory-mountain.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQJBQEb6N5gGTAHeAeyAI-7yMYRXkwYuM',
    appId: '1:94784010028:ios:1e2458296a14f7a841de89',
    messagingSenderId: '94784010028',
    projectId: 'theory-mountain',
    storageBucket: 'theory-mountain.appspot.com',
    androidClientId: '94784010028-itqp1ihi74ifoebo7o5un5i4n3l0icjv.apps.googleusercontent.com',
    iosClientId: '94784010028-g2t1s37ilhfgdf0hk599mdj73jmrqnvu.apps.googleusercontent.com',
    iosBundleId: 'io.noodler.theoryMountain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQJBQEb6N5gGTAHeAeyAI-7yMYRXkwYuM',
    appId: '1:94784010028:ios:1e2458296a14f7a841de89',
    messagingSenderId: '94784010028',
    projectId: 'theory-mountain',
    storageBucket: 'theory-mountain.appspot.com',
    androidClientId: '94784010028-itqp1ihi74ifoebo7o5un5i4n3l0icjv.apps.googleusercontent.com',
    iosClientId: '94784010028-g2t1s37ilhfgdf0hk599mdj73jmrqnvu.apps.googleusercontent.com',
    iosBundleId: 'io.noodler.theoryMountain',
  );
}
